import { chromium } from "playwright-core";
import { mkdirSync } from "node:fs";
const origin = process.env.ORIGIN!; const out = process.env.OUT!; mkdirSync(out, { recursive: true });
const browser = await chromium.launch();
const ctx = await browser.newContext({ viewport: { width: 1280, height: 800 }, colorScheme: "dark" });
await ctx.addInitScript(() => localStorage.setItem("herdr-web-ui:settings", JSON.stringify({ language: "en", theme: "dark" })));
const page = await ctx.newPage();
await page.goto(origin);
await page.locator(".conn-live").waitFor({ timeout: 20000 }).catch(() => console.log("no conn-live"));
await page.waitForTimeout(800);
// a row whose workspace sits in a git repository: the one that names herdr-br
const row = page.locator(".pane-item", { hasText: "herdr-br" }).first();
await row.hover();
await row.locator(".row-menu-toggle").click();
await page.getByRole("menu").waitFor();
await page.screenshot({ path: `${out}/menu.png` });
console.log("menu items:", await page.getByRole("menuitem").allTextContents());
await page.getByRole("menuitem", { name: "New worktree", exact: true }).click();
await page.getByRole("dialog", { name: /^New worktree/ }).waitFor();
await page.getByLabel(/^Branch/).fill("feature/row-menu");
await page.waitForTimeout(200);
await page.screenshot({ path: `${out}/new-worktree.png` });
await page.keyboard.press("Escape");
await page.getByRole("dialog", { name: /^New worktree/ }).waitFor({ state: "detached" });
console.log("focus after escape:", await page.evaluate(() => document.activeElement?.className));
await row.hover(); await row.locator(".row-menu-toggle").click();
await page.getByRole("menuitem", { name: "Open worktree…", exact: true }).click();
const open = page.getByRole("dialog", { name: /^Open worktree/ });
await open.waitFor();
await page.waitForTimeout(1500);
await page.screenshot({ path: `${out}/open-worktree.png` });
console.log("rows:", await open.locator(".worktree-row").count(), "pills:", await open.locator(".pill").allTextContents());
await page.keyboard.press("Escape");
await ctx.close(); await browser.close(); console.log("done");
